# Generated by Django 6.0.5 on 2026-05-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_record_id', models.CharField(max_length=120)),
                ('source_payload', models.JSONField(default=dict)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(max_length=64)),
                ('subcategory', models.CharField(blank=True, max_length=64)),
                ('activity_start', models.DateField()),
                ('activity_end', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('facility_code', models.CharField(blank=True, max_length=64)),
                ('facility_name', models.CharField(blank=True, max_length=200)),
                ('quantity_original', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_original', models.CharField(max_length=40)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_normalized', models.CharField(max_length=40)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('travel_origin', models.CharField(blank=True, max_length=3)),
                ('travel_destination', models.CharField(blank=True, max_length=3)),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=40)),
                ('emissions_kgco2e', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('initiated_by', models.CharField(default='system', max_length=120)),
                ('state', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=260)),
                ('row_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('lock', 'Lock'), ('edit', 'Edit')], max_length=20)),
                ('actor', models.CharField(default='system', max_length=120)),
                ('comment', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.activityrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='system', max_length=120)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.activityrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PlantMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant_code', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_mappings', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sap_plant_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityrecord',
            unique_together={('tenant', 'source_system', 'source_record_id')},
        ),
    ]
